### ISSUE TITLE
"RedisClient::ProtocolError: Unknown sigil type" using TLS

### ISSUE THREAD

**Issue by alexalouit** [redis-rb/redis-client#219]
As soon as we moved to TLS connection, pub/sub client returned this stacktrace 
```
RedisClient::ProtocolError (Unknown sigil type: "9" (rediss://..)):
redis-client (0.22.2) lib/redis_client/ruby_connection.rb:101:in `rescue in read'
redis-client (0.22.2) lib/redis_client/ruby_connection.rb:94:in `read'
redis-client (0.22.2) lib/redis_client.rb:513:in `next_event'
redis (5.3.0) lib/redis/subscribe.rb:66:in `subscription'
redis (5.3.0) lib/redis/subscribe.rb:29:in `psubscribe_with_timeout'
redis (5.3.0) lib/redis.rb:173:in `_subscription'
redis (5.3.0) lib/redis/commands/pubsub.rb:43:in `psubscribe_with_timeout'
```

```
RedisClient::ProtocolError (Unknown sigil type: "e" (rediss://..)):
RedisClient::ProtocolError (Unknown sigil type: "f" (rediss://..)):
RedisClient::ProtocolError (Unknown sigil type: "0" (rediss://..)):
RedisClient::ProtocolError (Unknown sigil type: "1" (rediss://..)):
```

Server is running version 7.4.0.
 
Any idea what's going on?

**Comment by byroot** [comment]
Hard to tell with this little info, but looks like the client isn't actually connecting with SSL and is trying to parse the encrypted stream as an clear text.

**Comment by alexalouit** [comment]
Which is weird is it works 99% of time.
Is there a way to enable a debug mode or something?

**Comment by byroot** [comment]
There's not really a debug mode, but you can fork the gem and add all the debugs you want.
